apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: mimir
  labels:
    app: demo
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: metrics
      protocol: TCP
      targetPort: 8080
  selector:
    app: demo
