apiVersion: v2
appVersion: 1.3.2
description: Grafana Tempo in MicroService mode
home: https://grafana.com/docs/tempo/latest/
icon: https://raw.githubusercontent.com/grafana/tempo/master/docs/tempo/website/logo_and_name.png
maintainers:
- email: number101010@gmail.com
  name: joe-elliott
- email: 9215868@gmail.com
  name: swartz-k
- name: annanay25
- name: mdisibio
- name: dgzlopes
- name: mapno
name: tempo-distributed
sources:
- https://github.com/grafana/tempo
type: application
version: 0.16.10
