apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: demo
    app.kubernetes.io/managed-by: hand
    app.kubernetes.io/name: demo
  name: demo
  namespace: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: demo
      app.kubernetes.io/name: demo
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: demo
        app.kubernetes.io/name: demo
    spec:
      containers:
      - image: yourregistry/tracedemo:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: OTEL_SERVICE_NAME
          value: demo
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://tempo-distributed-distributor:55681
        name: demo
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: docker-config
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30