apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: demo
  namespace: mimir
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: demo